## ***Exploratory Data Analysis***

Understanding the dataset to explore how the data is present in the database and if there is a need of creating some aggregated tables that can help with:

- Vendor selection for profitability
- Product Pricing Optimization

In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
#creating database connection

username = "root"
password = "password"
host = "localhost"
port = 3306
database = "vendor_performance"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

print("Database Connected Successfully")

Database Connected Successfully

In [3]:
# checking tables present in the database

query = "SHOW TABLES"
tables = pd.read_sql_query(query, engine)
tables

  Tables_in_vendor_performance
0              begin_inventory
1                end_inventory
2              purchase_prices
3                    purchases
4                        sales
5               vendor_invoice

In [4]:
for table in tables['Tables_in_vendor_performance']:
    print('-'*50, f'{table}', '-*50')
    print('Count of records :',pd.read_sql(f"SELECT COUNT(*) as count from {table}", engine)['count'].values[0])
    display(pd.read_sql(f"SELECT * FROM {table} limit 5", engine))

-------------------------------------------------- begin_inventory -*50
Count of records : 206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

-------------------------------------------------- end_inventory -*50
Count of records : 224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

-------------------------------------------------- purchase_prices -*50
Count of records : 12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

-------------------------------------------------- purchases -*50
Count of records : 2372474

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

-------------------------------------------------- sales -*50
Count of records : 12825363

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

-------------------------------------------------- vendor_invoice -*50
Count of records : 5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

In [5]:
purchases = pd.read_sql_query("SELECT * FROM purchases WHERE VendorNumber = 4466", engine)
purchases

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
1,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
2,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
3,38_GOULCREST_5215,38,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-07,2024-01-19,2024-02-26,9.41,6,56.46,1
4,59_CLAETHORPES_5215,59,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-05,2024-01-19,2024-02-26,9.41,6,56.46,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,81_PEMBROKE_5215,81,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-29,2025-01-04,2025-02-10,9.41,6,56.46,1
2188,62_KILMARNOCK_5255,62,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.35,5,46.75,1
2189,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.41,5,47.05,1
2190,6_GOULCREST_5215,6,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-31,2025-01-04,2025-02-10,9.41,6,56.46,1
2191,35_HALIVAARA_5255,35,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-27,2025-01-04,2025-02-10,9.35,5,46.75,1

In [6]:
purchase_prices = pd.read_sql_query("SELECT * FROM purchase_prices where VendorNumber = 4466", engine)
purchase_prices

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
1,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
2,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE

In [7]:
vendor_invoice = pd.read_sql_query("SELECT * FROM vendor_invoice WHERE VendorNumber = 4466", engine)
vendor_invoice

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-19,8207,2023-12-27,2024-02-26,335,3142.33,16.97,None
2,4466,AMERICAN VINTAGE BEVERAGE,2024-01-18,8307,2024-01-03,2024-02-18,41,383.35,1.99,None
3,4466,AMERICAN VINTAGE BEVERAGE,2024-01-27,8469,2024-01-14,2024-03-11,72,673.20,3.30,None
4,4466,AMERICAN VINTAGE BEVERAGE,2024-02-04,8532,2024-01-19,2024-03-15,79,740.21,3.48,None
5,4466,AMERICAN VINTAGE BEVERAGE,2024-02-09,8604,2024-01-24,2024-03-15,347,3261.37,17.61,None
6,4466,AMERICAN VINTAGE BEVERAGE,2024-02-17,8793,2024-02-05,2024-04-02,72,675.36,3.17,None
7,4466,AMERICAN VINTAGE BEVERAGE,2024-03-01,8892,2024-02-12,2024-03-28,117,1096.05,5.15,None
8,4466,AMERICAN VINTAGE BEVERAGE,2024-03-07,8995,2024-02-19,2024-04-02,129,1209.27,5.44,None
9,4466,AMERICAN VINTAGE BEVERAGE,2024-03-12,9033,2024-02-22,2024-04-16,147,1377.87,6.61,None
10,4466,AMERICAN VINTAGE BEVERAGE,2024-03-16,9180,2024-03-03,2024-04-19,211,1979.33,9.50,None
11,4466,AMERICAN VINTAGE BEVERAGE,2024-03-23,9244,2024-03-08,2024-04-21,161,1510.69,6.95,None
12,4466,AMERICAN VINTAGE BEVERAGE,2024-03-31,9371,2024-03-17,2024-05-13,176,1649.20,8.91,None
13,4466,AMERICAN VINTAGE BEVERAGE,2024-04-09,9491,2024-03-24,2024-05-08,215,2016.43,10.08,None
14,4466,AMERICAN VINTAGE BEVERAGE,2024-04-17,9583,2024-03-31,2024-05-12,110,1035.10,5.69,None
15,4466,AMERICAN VINTAGE BEVERAGE,2024-04-20,9639,2024-04-04,2024-06-04,515,5323.01,25.02,None
16,4466,AMERICAN VINTAGE BEVERAGE,2024-04-29,9800,2024-04-15,2024-06-07,275,2775.01,13.60,None
17,4466,AMERICAN VINTAGE BEVERAGE,2024-05-09,9886,2024-04-21,2024-06-12,312,3050.86,13.73,None
18,4466,AMERICAN VINTAGE BEVERAGE,2024-05-14,9999,2024-04-29,2024-06-26,310,3117.82,14.97,None
19,4466,AMERICAN VINTAGE BEVERAGE,2024-05-16,10095,2024-05-06,2024-06-27,215,2123.01,11.46,None
20,4466,AMERICAN VINTAGE BEVERAGE,2024-05-28,10169,2024-05-11,2024-07-04,327,3298.55,15.83,None
21,4466,AMERICAN VINTAGE BEVERAGE,2024-06-04,10257,2024-05-17,2024-07-08,376,3708.18,20.39,None
22,4466,AMERICAN VINTAGE BEVERAGE,2024-06-12,10346,2024-05-23,2024-07-20,640,6458.38,29.71,None
23,4466,AMERICAN VINTAGE BEVERAGE,2024-06-17,10445,2024-05-30,2024-07-19,288,2937.56,15.86,None
24,4466,AMERICAN VINTAGE BEVERAGE,2024-06-22,10600,2024-06-09,2024-08-01,308,3213.28,17.03,None
25,4466,AMERICAN VINTAGE BEVERAGE,2024-06-29,10695,2024-06-16,2024-08-12,143,1585.75,8.09,None
26,4466,AMERICAN VINTAGE BEVERAGE,2024-07-09,10777,2024-06-22,2024-08-15,18,179.88,0.99,None
27,4466,AMERICAN VINTAGE BEVERAGE,2024-07-08,10836,2024-06-25,2024-08-14,8,85.96,0.43,None
28,4466,AMERICAN VINTAGE BEVERAGE,2024-07-11,10969,2024-06-29,2024-08-18,94,993.12,5.06,None
29,4466,AMERICAN VINTAGE BEVERAGE,2024-07-19,11085,2024-07-06,2024-09-04,601,5883.09,31.18,None
30,4466,AMERICAN VINTAGE BEVERAGE,2024-07-26,11187,2024-07-14,2024-08-26,1535,15406.69,77.03,None
31,4466,AMERICAN VINTAGE BEVERAGE,2024-08-03,11244,2024-07-18,2024-09-04,266,2888.22,15.31,None
32,4466,AMERICAN VINTAGE BEVERAGE,2024-08-11,11362,2024-07-26,2024-09-24,206,2171.64,11.08,None
33,4466,AMERICAN VINTAGE BEVERAGE,2024-08-18,11489,2024-08-04,2024-09-16,768,7292.98,37.92,None
34,4466,AMERICAN VINTAGE BEVERAGE,2024-08-24,11540,2024-08-08,2024-10-02,1207,12242.43,64.88,None
35,4466,AMERICAN VINTAGE BEVERAGE,2024-09-02,11716,2024-08-19,2024-09-29,433,4334.43,20.37,None
36,4466,AMERICAN VINTAGE BEVERAGE,2024-09-12,11771,2024-08-23,2024-10-11,370,3640.18,18.20,None
37,4466,AMERICAN VINTAGE BEVERAGE,2024-09-20,11901,2024-09-01,2024-10-30,358,3626.74,16.32,None
38,4466,AMERICAN VINTAGE BEVERAGE,2024-09-25,11993,2024-09-07,2024-10-23,233,2264.85,12.23,None
39,4466,AMERICAN VINTAGE BEVERAGE,2024-10-01,12125,2024-09-16,2024-11-07,284,2813.46,15.47,None
40,4466,AMERICAN VINTAGE BEVERAGE,2024-10-08,12235,2024-09-23,2024-11-20,258,2592.08,11.92,None
41,4466,AMERICAN VINTAGE BEVERAGE,2024-10-09,12253,2024-09-23,2024-11-14,1,11.19,0.05,None
42,4466,AMERICAN VINTAGE BEVERAGE,2024-10-12,12321,2024-09-26,2024-11-19,172,1685.98,7.59,None
43,4466,AMERICAN VINTAGE BEVERAGE,2024-10-20,12466,2024-10-05,2024-11-26,280,2798.60,14.55,None
44,4466,AMERICAN VINTAGE BEVERAGE,2024-10-27,12515,2024-10-09,2024-11-30,178,1763.28,8.64,None
45,4466,AMERICAN VINTAGE BEVERAGE,2024-11-07,12702,2024-10-21,2024-12-11,183,1812.77,8.70,None
46,4466,AMERICAN VINTAGE BEVERAGE,2024-11-12,12752,2024-10-25,2024-12-11,216,2156.16,10.57,None
47,4466,AMERICAN VINTAGE BEVERAGE,2024-11-20,12828,2024-10-30,2024-12-18,262,2597.36,12.99,None
48,4466,AMERICAN VINTAGE BEVERAGE,2024-11-27,12929,2024-11-06,2025-01-04,270,2622.32,12.85,None
49,4466,AMERICAN VINTAGE BEVERAGE,2024-11-28,13092,2024-11-16,2024-12-30,209,2036.17,11.20,None
50,4466,AMERICAN VINTAGE BEVERAGE,2024-12-06,13134,2024-11-20,2025-01-18,305,3018.89,15.70,None
51,4466,AMERICAN VINTAGE BEVERAGE,2024-12-16,13254,2024-11-28,2025-01-13,262,2530.36,11.39,None
52,4466,AMERICAN VINTAGE BEVERAGE,2024-12-26,13432,2024-12-09,2025-01-27,231,2263.43,11.32,None
53,4466,AMERICAN VINTAGE BEVERAGE,2024-12-30,13483,2024-12-13,2025-02-11,221,2178.27,11.33,None
54,4466,AMERICAN VINTAGE BEVERAGE,2025-01-09,13627,2024-12-22,2025-02-05,413,3985.03,19.53,None

In [8]:
sales = pd.read_sql_query("SELECT * FROM sales WHERE VendorNo = 4466", engine)
sales

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-09,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
1,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-12,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
2,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-15,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
3,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-21,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
4,1_HARDERSFIELD_5215,1,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-01-23,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9448,9_BLACKPOOL_5215,9,5215,TGI Fridays Long Island Iced,1.75L,1,12.99,12.99,2024-12-21,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9449,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-02,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9450,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-09,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9451,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-23,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE
9452,9_BLACKPOOL_5255,9,5255,TGI Fridays Ultimte Mudslide,1.75L,1,12.99,12.99,2024-12-31,1750.0,1,1.84,4466,AMERICAN VINTAGE BEVERAGE

In [9]:
vendor_invoice['PONumber'].nunique()

55

In [10]:
vendor_invoice.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='str')

In [11]:
sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='str')

In [12]:
purchases.groupby(['Brand', 'PurchasePrice'])[['Quantity', 'Dollars']].sum()

                     Quantity   Dollars
Brand PurchasePrice
3140  11.19              4640  51921.60
5215  9.41               4923  46325.43
5255  9.35               6215  58110.25

In [13]:
sales.groupby('Brand')[['SalesDollars', 'SalesPrice', 'SalesQuantity']].sum()

       SalesDollars  SalesPrice  SalesQuantity
Brand
3140       50531.10    30071.85           3890
5215       60416.49    41542.02           4651
5255       79187.04    51180.60           6096

- The ***purchases*** table contains actual purchase data, including the date of purchase, products (brands) purchased by the vendors, the amount paid (in dollars), and the quantity purchased
- The purchase price column is derived from the ***purchase_prices*** table, which provides product-wise actual purchase prices. The combination of vendor and brand is unique in this table.
- The ***vendor_invoice*** table aggregates data from the purchases table, summarizing quantity and dollar amounts, along with an additional column for freight. This table  maintains uniqueness based on vendor and PO number.
- The ***sales*** table captures actual sales transactions, detailing the brands purchased by vendors, the quantity sold, the selling price, and the revenue earned.

As the data the we need for analysis is distributed in different tables, we need to create summary table containing:

- purchase transactions made by vendors
- sales transaction data
- freights costs for each vendors
- actual product prices from vendors

In [14]:
vendor_invoice.columns

Index(['VendorNumber', 'VendorName', 'InvoiceDate', 'PONumber', 'PODate',
       'PayDate', 'Quantity', 'Dollars', 'Freight', 'Approval'],
      dtype='str')

In [15]:
freight_summary = pd.read_sql_query("""SELECT VendorNumber, SUM(Freight) as FreightCost 
FROM vendor_invoice 
GROUP BY VendorNumber""", engine)
freight_summary

     VendorNumber  FreightCost
0             105        62.39
1            4466       793.91
2             388       211.74
3             480     89286.27
4             516      8510.41
..            ...          ...
121        201359         0.09
122          4901         0.72
123         90059        74.84
124          5083        10.68
125            54         0.48

[126 rows x 2 columns]

In [16]:
purchases.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'VendorNumber',
       'VendorName', 'PONumber', 'PODate', 'ReceivingDate', 'InvoiceDate',
       'PayDate', 'PurchasePrice', 'Quantity', 'Dollars', 'Classification'],
      dtype='str')

In [17]:
purchase_prices.columns

Index(['Brand', 'Description', 'Price', 'Size', 'Volume', 'Classification',
       'PurchasePrice', 'VendorNumber', 'VendorName'],
      dtype='str')

In [18]:
pd.read_sql_query("""SELECT p.VendorNumber,
p.VendorName,
p.Brand,
p.PurchasePrice,
pp.Volume,
pp.Price as ActualPrice,
Sum(p.Quantity) as TotalPurchaseQuantity, 
SUM(p.Dollars) as TotalPurchaseDollars
FROM purchases p 
JOIN purchase_prices pp
ON p.Brand = pp.Brand
WHERE p.PurchasePrice > 0
GROUP BY p.VendorNumber, p.VendorName, p.Brand,p.PurchasePrice, pp.Volume, pp.Price
ORDER BY TotalPurchaseDollars""", engine)

,VendorNumber,VendorName,Brand,PurchasePrice,Volume,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars
0,7245,PROXIMO SPIRITS INC.,3065,0.71,50,0.99,1.0,0.71
1,3960,DIAGEO NORTH AMERICA INC,6127,1.47,200,1.99,1.0,1.47
2,3924,HEAVEN HILL DISTILLERIES,9123,0.74,50,0.99,2.0,1.48
3,8004,SAZERAC CO INC,5683,0.39,50,0.49,6.0,2.34
4,9815,WINE GROUP INC,8527,1.32,750,4.99,2.0,2.64
...,...,...,...,...,...,...,...,...
10687,3960,DIAGEO NORTH AMERICA INC,3545,21.89,1750,29.99,138109.0,3023206.01
10688,3960,DIAGEO NORTH AMERICA INC,4261,16.17,1750,22.99,201682.0,3261197.94
10689,17035,PERNOD RICARD USA,8068,18.24,1750,24.99,187407.0,3418303.68
10690,4425,MARTIGNETTI COMPANIES,3405,23.19,1750,28.99,164038.0,3804041.22
10691,1128,BROWN-FORMAN CORP,1233,26.27,1750,36.99,145080.0,3811251.60

In [19]:
sales.columns

Index(['InventoryId', 'Store', 'Brand', 'Description', 'Size', 'SalesQuantity',
       'SalesDollars', 'SalesPrice', 'SalesDate', 'Volume', 'Classification',
       'ExciseTax', 'VendorNo', 'VendorName'],
      dtype='str')

In [20]:
pd.read_sql_query("""SELECT 
VendorNo,
Brand,
SUM(SalesPrice) as TotalSalesPrice,
SUM(SalesDollars) as TotalSalesDollars,
SUM(SalesQuantity) as TotalSalesQuantity,
SUM(ExciseTax) as TotalExciseTax
FROM sales
GROUP BY VendorNo, Brand
ORDER BY TotalSalesPrice""", engine)

,VendorNo,Brand,TotalSalesPrice,TotalSalesDollars,TotalSalesQuantity,TotalExciseTax
0,8004,5341,0.49,5.390000e+00,11.0,0.58
1,8004,5287,0.98,9.800000e-01,2.0,0.10
2,3252,3933,0.99,1.980000e+00,2.0,0.10
3,3924,9123,0.99,1.980000e+00,2.0,0.10
4,9206,2773,0.99,9.900000e-01,1.0,0.05
...,...,...,...,...,...,...
11267,480,3857,589137.79,1.699670e+06,32945.0,60533.43
11268,3960,8680,596574.93,1.884307e+06,47966.0,88129.80
11269,17035,2589,614529.34,2.773368e+06,69627.0,127931.67
11270,9165,3650,662320.04,2.009509e+06,41639.0,32783.09
11271,1128,1233,672819.31,5.101920e+06,142049.0,260999.20

### Combining above three queries and creating an Aggregated Table named as ***FINAL TABLE***

In [21]:
import time
start = time.time()
final_table = pd.read_sql_query("""SELECT 
    pp.VendorNumber,
    pp.Brand,
    pp.Price as ActualPrice,
    pp.PurchasePrice,
    SUM(s.SalesPrice) as TotalSalesPrice,
    SUM(s.SalesDollars) as TotalSalesDollars,
    SUM(s.SalesQuantity) as TotalSalesQuantity,
    SUM(s.ExciseTax) as TotalExciseTax,
    Sum(vi.Quantity) as TotalPurchaseQuantity, 
    SUM(vi.Dollars) as TotalPurchaseDollars,
    SUM(vi.Freight) as TotalFreightCost
FROM purchase_prices pp
JOIN sales s
    ON pp.VendorNumber = s.VendorNo
    AND pp.Brand = s.Brand
JOIN vendor_invoice vi
    ON pp.VendorNumber = vi.VendorNumber
GROUP BY pp.VendorNumber, pp.Brand, pp.Price, pp.PurchasePrice
""", engine)
end = time.time()

In [27]:
totaltime = (end-start)/60
totaltime

12.89756531715393

In [26]:
final_table

,VendorNumber,Brand,ActualPrice,PurchasePrice,TotalSalesPrice,TotalSalesDollars,TotalSalesQuantity,TotalExciseTax,TotalPurchaseQuantity,TotalPurchaseDollars,TotalFreightCost
0,8112,115,27.99,21.37,7.489424e+06,1.578706e+07,564025.0,5.922262e+05,2.081573e+09,4.608612e+10,2.352094e+08
1,480,126,32.99,20.14,1.617272e+07,9.551360e+07,3190715.0,3.350251e+06,1.348729e+10,1.665680e+11,8.438445e+08
2,1128,171,49.99,36.76,1.302615e+07,1.861388e+07,362450.0,6.662513e+05,4.624137e+09,6.218127e+10,3.152933e+08
3,7245,175,36.99,26.80,1.351028e+06,1.667423e+06,39710.0,3.131755e+04,3.989946e+08,4.438997e+09,2.281195e+07
4,4425,211,24.99,19.83,4.477826e+06,5.755095e+06,204344.0,1.611284e+05,5.114476e+09,5.396809e+10,2.807279e+08
...,...,...,...,...,...,...,...,...,...,...,...
11217,9552,27171,15.99,10.88,1.099313e+05,1.626983e+05,10175.0,1.125850e+03,1.716051e+08,1.366977e+09,6.943978e+06
11218,3960,3014,12.99,10.15,1.428900e+04,2.214795e+04,1705.0,1.342550e+03,1.091958e+08,1.019196e+09,5.140641e+06
11219,7239,4785,74.99,53.95,3.635021e+05,1.168049e+06,15070.0,5.920200e+03,1.238558e+07,2.918814e+08,1.477144e+06
11220,9552,1164,29.99,23.80,1.649450e+03,9.896700e+03,330.0,2.596000e+02,1.372841e+06,1.093582e+07,5.555182e+04
11221,4692,27789,79.99,51.61,4.399450e+03,8.798900e+03,110.0,1.210000e+01,1.610020e+05,1.808146e+06,9.139380e+03

## Here's more organized code if the above code doesn't run due to heavy data

In [25]:
vendor_sales_summary = pd.read_sql_query("""
WITH FreightSummary as (
    SELECT
        VendorNumber,
        SUM(Freight) as FreightCost
    FROM vendor_invoice
    GROUP BY VendorNumber
),

PurchaseSummary as (
    SELECT 
        p.VendorNumber,
        p.VendorName,
        p.Brand,
        p.Description,
        p.PurchasePrice,
        pp.Price as ActualPrice,
        pp.Volume,
        Sum(p.Quantity) as TotalPurchaseQuantity, 
        SUM(p.Dollars) as TotalPurchaseDollars
    FROM purchases p
    JOIN purchase_prices pp
        ON p.Brand = pp.Brand
    WHERE p.PurchasePrice > 0
    GROUP BY p.VendorNumber,p.VendorName, p.Brand, p.Description, p.PurchasePrice, pp.Price, pp.Volume
),

SalesSummary as (
    SELECT
        VendorNo,
        Brand,
        SUM(SalesPrice) as TotalSalesPrice,
        SUM(SalesDollars) as TotalSalesDollars,
        SUM(SalesQuantity) as TotalSalesQuantity,
        SUM(ExciseTax) as TotalExciseTax
    FROM sales
    GROUP BY VendorNo, Brand
)

SELECT
    ps.VendorNumber,
    ps.VendorName,
    ps.Brand,
    ps.Description,
    ps.PurchasePrice,
    ps.ActualPrice,
    ps.Volume,
    ps.TotalPurchaseQuantity, 
    ps.TotalPurchaseDollars,
    ss.TotalSalesPrice,
    ss.TotalSalesDollars,
    ss.TotalSalesQuantity,
    ss.TotalExciseTax,
    fs.FreightCost
FROM PurchaseSummary ps
LEFT JOIN SalesSummary ss
    ON ps.VendorNumber = ss.VendorNo
    AND ps.Brand = ss.Brand
LEFT JOIN FreightSummary fs
    ON ps.VendorNumber = fs.VendorNumber
ORDER BY ps.TotalPurchaseDollars DESC
""", engine)

vendor_sales_summary

,VendorNumber,VendorName,Brand,Description,PurchasePrice,ActualPrice,Volume,TotalPurchaseQuantity,TotalPurchaseDollars,TotalSalesPrice,TotalSalesDollars,TotalSalesQuantity,TotalExciseTax,FreightCost
0,1128,BROWN-FORMAN CORP,1233,Jack Daniels No 7 Black,26.27,36.99,1750,145080.0,3811251.60,672819.31,5.101920e+06,142049.0,260999.20,68601.68
1,4425,MARTIGNETTI COMPANIES,3405,Tito's Handmade Vodka,23.19,28.99,1750,164038.0,3804041.22,561512.37,4.819073e+06,160247.0,294438.66,144929.24
2,17035,PERNOD RICARD USA,8068,Absolut 80 Proof,18.24,24.99,1750,187407.0,3418303.68,461140.15,4.538121e+06,187140.0,343854.07,123780.22
3,3960,DIAGEO NORTH AMERICA INC,4261,Capt Morgan Spiced Rum,16.17,22.99,1750,201682.0,3261197.94,420050.01,4.475973e+06,200412.0,368242.80,257032.07
4,3960,DIAGEO NORTH AMERICA INC,3545,Ketel One Vodka,21.89,29.99,1750,138109.0,3023206.01,545778.28,4.223108e+06,135838.0,249587.83,257032.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10687,9815,WINE GROUP INC,8527,Concannon Glen Ellen Wh Zin,1.32,4.99,750,2.0,2.64,10.96,1.595000e+01,5.0,0.55,27100.41
10688,8004,SAZERAC CO INC,5683,Dr McGillicuddy's Apple Pie,0.39,0.49,50,6.0,2.34,1.47,6.566000e+01,134.0,7.04,50293.62
10689,3924,HEAVEN HILL DISTILLERIES,9123,Deep Eddy Vodka,0.74,0.99,50,2.0,1.48,0.99,1.980000e+00,2.0,0.10,14069.87
10690,3960,DIAGEO NORTH AMERICA INC,6127,The Club Strawbry Margarita,1.47,1.99,200,1.0,1.47,77.61,1.432800e+02,72.0,15.12,257032.07
10691,7245,PROXIMO SPIRITS INC.,3065,Three Olives Grape Vodka,0.71,0.99,50,1.0,0.71,33.66,8.514000e+01,86.0,4.46,38994.78

This query generates a vendor-wise sales and purchase summary, which is valuable for:
### **Performance Optimization**:
- The query involves heavy joins and aggregations on large datasets like **sales** and **purchases**.
- Storing the pre-aggregated results avoids repeated expensive computations.
- Helps in analyzing sales, purchases, and pricing for different vendors and brands.
- Future Benefits of Storing this data for faster Dashboarding & Reporting.
- Instead of running expensive query each time, dashboards can fetch data quickly from **vendor_sales_summary**

Now,
Checking if the **FINAL TABLE** is inconsistent for furthur analysis.
In more simple words lets check if the data is clean or not.

In [28]:
vendor_sales_summary.dtypes

VendorNumber               int64
VendorName                   str
Brand                      int64
Description                  str
PurchasePrice            float64
ActualPrice              float64
Volume                       str
TotalPurchaseQuantity    float64
TotalPurchaseDollars     float64
TotalSalesPrice          float64
TotalSalesDollars        float64
TotalSalesQuantity       float64
TotalExciseTax           float64
FreightCost              float64
dtype: object

In [29]:
vendor_sales_summary.isnull().sum()

VendorNumber               0
VendorName                 0
Brand                      0
Description                0
PurchasePrice              0
ActualPrice                0
Volume                     0
TotalPurchaseQuantity      0
TotalPurchaseDollars       0
TotalSalesPrice          178
TotalSalesDollars        178
TotalSalesQuantity       178
TotalExciseTax           178
FreightCost                0
dtype: int64

In [31]:
vendor_sales_summary['VendorName'].unique()

<ArrowStringArray>
['BROWN-FORMAN CORP          ',       'MARTIGNETTI COMPANIES',
 'PERNOD RICARD USA          ', 'DIAGEO NORTH AMERICA INC   ',
 'BACARDI USA INC            ', 'JIM BEAM BRANDS COMPANY    ',
 'MAJESTIC FINE WINES        ', 'ULTRA BEVERAGE COMPANY LLP ',
 'STOLI GROUP,(USA) LLC      ', 'PROXIMO SPIRITS INC.       ',
 ...
             'UNCORKED       ', 'BRONCO WINE COMPANY        ',
 'MILTONS DISTRIBUTING CO    ', 'TRUETT HURST               ',
 'LAUREATE IMPORTS CO        ', 'FANTASY FINE WINES CORP    ',
 'AAPER ALCOHOL & CHEMICAL CO', 'SILVER MOUNTAIN CIDERS     ',
 'CAPSTONE INTERNATIONAL     ', 'FLAVOR ESSENCE INC         ']
Length: 129, dtype: str

In [33]:
vendor_sales_summary['Description'].unique()

<ArrowStringArray>
[    'Jack Daniels No 7 Black',       'Tito's Handmade Vodka',
            'Absolut 80 Proof',      'Capt Morgan Spiced Rum',
             'Ketel One Vodka',            'Grey Goose Vodka',
       'Jameson Irish Whiskey',           'Smirnoff Traveler',
                   'Tanqueray',                    'Jim Beam',
 ...
         'Riunite Sweet White',         'Firefly Ridge Chard',
           'Debauchery Pnt Nr', 'Terruzzi & Puthod Vernaccia',
  'Santa Rita Organic Svgn Bl',    'Aresti Pnt Nr Curico Vly',
   'Smirnoff Light Strawberry',           'Crown Royal Apple',
 'Concannon Glen Ellen Wh Zin', 'The Club Strawbry Margarita']
Length: 9651, dtype: str

### We found inconsistency in the data so let's look forward to resolve them

### Changing data type of Volume column from String to FLOAT64

In [36]:
vendor_sales_summary['Volume'] = pd.to_numeric(vendor_sales_summary['Volume'], errors='coerce')

In [55]:
vendor_sales_summary['Volume'].fillna(0)

0        1750.0
1        1750.0
2        1750.0
3        1750.0
4        1750.0
          ...
10687     750.0
10688      50.0
10689      50.0
10690     200.0
10691      50.0
Name: Volume, Length: 10692, dtype: float64

### Removing extra spaces from Vendor's Name

In [42]:
vendor_sales_summary['VendorName'] = vendor_sales_summary['VendorName'].str.strip()

In [43]:
vendor_sales_summary['VendorName'].unique()

<ArrowStringArray>
[          'BROWN-FORMAN CORP',       'MARTIGNETTI COMPANIES',
           'PERNOD RICARD USA',    'DIAGEO NORTH AMERICA INC',
             'BACARDI USA INC',     'JIM BEAM BRANDS COMPANY',
         'MAJESTIC FINE WINES',  'ULTRA BEVERAGE COMPANY LLP',
       'STOLI GROUP,(USA) LLC',        'PROXIMO SPIRITS INC.',
 ...
                    'UNCORKED',         'BRONCO WINE COMPANY',
     'MILTONS DISTRIBUTING CO',                'TRUETT HURST',
         'LAUREATE IMPORTS CO',     'FANTASY FINE WINES CORP',
 'AAPER ALCOHOL & CHEMICAL CO',      'SILVER MOUNTAIN CIDERS',
      'CAPSTONE INTERNATIONAL',          'FLAVOR ESSENCE INC']
Length: 128, dtype: str

### Creating new columns/features for better analysis

In [44]:
vendor_sales_summary['GrossProfit'] = vendor_sales_summary['TotalSalesDollars'] - vendor_sales_summary['TotalPurchaseDollars']

In [46]:
vendor_sales_summary['ProfitMargin'] = (vendor_sales_summary['GrossProfit'] / vendor_sales_summary['TotalSalesDollars']) * 100

In [49]:
vendor_sales_summary['StockTurnover'] =  vendor_sales_summary['TotalSalesQuantity'] / vendor_sales_summary['TotalPurchaseQuantity']

In [50]:
vendor_sales_summary['SalesToPurchaseRation'] = vendor_sales_summary['TotalSalesDollars'] / vendor_sales_summary['TotalPurchaseDollars']

In [51]:
vendor_sales_summary = vendor_sales_summary.rename(columns={'SalesToPurchaseRation': 'SalestoPurchaseRatio'})

### Uploading the analyzed data in another table

In [57]:
vendor_sales_summary.to_sql(
    name='vendor_sales_summary',
    con=engine,
    if_exists="replace",
    index=False
)

DatabaseError: Execution failed on sql 'INSERT INTO vendor_sales_summary ("VendorNumber", "VendorName", "Brand", "Description", "PurchasePrice", "ActualPrice", "Volume", "TotalPurchaseQuantity", "TotalPurchaseDollars", "TotalSalesPrice", "TotalSalesDollars", "TotalSalesQuantity", "TotalExciseTax", "FreightCost", "GrossProfit", "ProfitMargin", "StockTurnover", "SalestoPurchaseRatio") VALUES (:VendorNumber, :VendorName, :Brand, :Description, :PurchasePrice, :ActualPrice, :Volume, :TotalPurchaseQuantity, :TotalPurchaseDollars, :TotalSalesPrice, :TotalSalesDollars, :TotalSalesQuantity, :TotalExciseTax, :FreightCost, :GrossProfit, :ProfitMargin, :StockTurnover, :SalestoPurchaseRatio)': (pymysql.err.ProgrammingError) -inf can not be used with MySQL
[SQL: INSERT INTO vendor_sales_summary (`VendorNumber`, `VendorName`, `Brand`, `Description`, `PurchasePrice`, `ActualPrice`, `Volume`, `TotalPurchaseQuantity`, `TotalPurchaseDollars`, `TotalSalesPrice`, `TotalSalesDollars`, `TotalSalesQuantity`, `TotalExciseTax`, `FreightCost`, `GrossProfit`, `ProfitMargin`, `StockTurnover`, `SalestoPurchaseRatio`) VALUES (%(VendorNumber)s, %(VendorName)s, %(Brand)s, %(Description)s, %(PurchasePrice)s, %(ActualPrice)s, %(Volume)s, %(TotalPurchaseQuantity)s, %(TotalPurchaseDollars)s, %(TotalSalesPrice)s, %(TotalSalesDollars)s, %(TotalSalesQuantity)s, %(TotalExciseTax)s, %(FreightCost)s, %(GrossProfit)s, %(ProfitMargin)s, %(StockTurnover)s, %(SalestoPurchaseRatio)s)]
[parameters: [{'VendorNumber': 1128, 'VendorName': 'BROWN-FORMAN CORP', 'Brand': 1233, 'Description': 'Jack Daniels No 7 Black', 'PurchasePrice': 26.27, 'ActualPrice': 36.99, 'Volume': 1750.0, 'TotalPurchaseQuantity': 145080.0, 'TotalPurchaseDollars': 3811251.600000111, 'TotalSalesPrice': 672819.3099998693, 'TotalSalesDollars': 5101919.510000559, 'TotalSalesQuantity': 142049.0, 'TotalExciseTax': 260999.2000000145, 'FreightCost': 68601.68000000001, 'GrossProfit': 1290667.9100004476, 'ProfitMargin': 25.297692514955152, 'StockTurnover': 0.9791080783016267, 'SalestoPurchaseRatio': 1.338646734841754}, {'VendorNumber': 4425, 'VendorName': 'MARTIGNETTI COMPANIES', 'Brand': 3405, 'Description': "Tito's Handmade Vodka", 'PurchasePrice': 23.19, 'ActualPrice': 28.99, 'Volume': 1750.0, 'TotalPurchaseQuantity': 164038.0, 'TotalPurchaseDollars': 3804041.2199999536, 'TotalSalesPrice': 561512.3699999085, 'TotalSalesDollars': 4819073.490000401, 'TotalSalesQuantity': 160247.0, 'TotalExciseTax': 294438.6600000097, 'FreightCost': 144929.24, 'GrossProfit': 1015032.270000447, 'ProfitMargin': 21.062809523586715, 'StockTurnover': 0.9768895012131336, 'SalestoPurchaseRatio': 1.2668299871893762}, {'VendorNumber': 17035, 'VendorName': 'PERNOD RICARD USA', 'Brand': 8068, 'Description': 'Absolut 80 Proof', 'PurchasePrice': 18.24, 'ActualPrice': 24.99, 'Volume': 1750.0, 'TotalPurchaseQuantity': 187407.0, 'TotalPurchaseDollars': 3418303.680000034, 'TotalSalesPrice': 461140.1499998849, 'TotalSalesDollars': 4538120.600000365, 'TotalSalesQuantity': 187140.0, 'TotalExciseTax': 343854.07000000787, 'FreightCost': 123780.21999999997, 'GrossProfit': 1119816.9200003305, 'ProfitMargin': 24.67578583081817, 'StockTurnover': 0.9985752933454993, 'SalestoPurchaseRatio': 1.3275943347433425}, {'VendorNumber': 3960, 'VendorName': 'DIAGEO NORTH AMERICA INC', 'Brand': 4261, 'Description': 'Capt Morgan Spiced Rum', 'PurchasePrice': 16.17, 'ActualPrice': 22.99, 'Volume': 1750.0, 'TotalPurchaseQuantity': 201682.0, 'TotalPurchaseDollars': 3261197.94000002, 'TotalSalesPrice': 420050.0099998967, 'TotalSalesDollars': 4475972.880000464, 'TotalSalesQuantity': 200412.0, 'TotalExciseTax': 368242.8000000149, 'FreightCost': 257032.07000000007, 'GrossProfit': 1214774.9400004437, 'ProfitMargin': 27.13990840803124, 'StockTurnover': 0.9937029581221923, 'SalestoPurchaseRatio': 1.3724934709116234}, {'VendorNumber': 3960, 'VendorName': 'DIAGEO NORTH AMERICA INC', 'Brand': 3545, 'Description': 'Ketel One Vodka', 'PurchasePrice': 21.89, 'ActualPrice': 29.99, 'Volume': 1750.0, 'TotalPurchaseQuantity': 138109.0, 'TotalPurchaseDollars': 3023206.0099999965, 'TotalSalesPrice': 545778.2799998876, 'TotalSalesDollars': 4223107.620000436, 'TotalSalesQuantity': 135838.0, 'TotalExciseTax': 249587.83000001253, 'FreightCost': 257032.07000000007, 'GrossProfit': 1199901.6100004395, 'ProfitMargin': 28.412764200414, 'StockTurnover': 0.9835564662693959, 'SalestoPurchaseRatio': 1.3968970708683002}, {'VendorNumber': 480, 'VendorName': 'BACARDI USA INC', 'Brand': 3858, 'Description': 'Grey Goose Vodka', 'PurchasePrice': 17.77, 'ActualPrice': 23.99, 'Volume': 750.0, 'TotalPurchaseQuantity': 138809.0, 'TotalPurchaseDollars': 2466635.930000039, 'TotalSalesPrice': 446932.08999989054, 'TotalSalesDollars': 3383912.4000005093, 'TotalSalesQuantity': 141860.0, 'TotalExciseTax': 111699.18999999705, 'FreightCost': 89286.26999999999, 'GrossProfit': 917276.4700004705, 'ProfitMargin': 27.10698036983264, 'StockTurnover': 1.0219798428055817, 'SalestoPurchaseRatio': 1.3718734730343671}, {'VendorNumber': 17035, 'VendorName': 'PERNOD RICARD USA', 'Brand': 2589, 'Description': 'Jameson Irish Whiskey', 'PurchasePrice': 30.76, 'ActualPrice': 39.99, 'Volume': 1750.0, 'TotalPurchaseQuantity': 70783.0, 'TotalPurchaseDollars': 2177285.0800000825, 'TotalSalesPrice': 614529.3399998964, 'TotalSalesDollars': 2773367.729999988, 'TotalSalesQuantity': 69627.0, 'TotalExciseTax': 127931.66999998408, 'FreightCost': 123780.21999999997, 'GrossProfit': 596082.6499999054, 'ProfitMargin': 21.493098212399982, 'StockTurnover': 0.9836683949535906, 'SalestoPurchaseRatio': 1.2737733590678364}, {'VendorNumber': 3960, 'VendorName': 'DIAGEO NORTH AMERICA INC', 'Brand': 3102, 'Description': 'Smirnoff Traveler', 'PurchasePrice': 12.94, 'ActualPrice': 17.99, 'Volume': 1750.0, 'TotalPurchaseQuantity': 161386.0, 'TotalPurchaseDollars': 2088334.8399999859, 'TotalSalesPrice': 292586.2899999302, 'TotalSalesDollars': 2592041.349999925, 'TotalSalesQuantity': 148265.0, 'TotalExciseTax': 272422.6000000083, 'FreightCost': 257032.07000000007, 'GrossProfit': 503706.50999993924, 'ProfitMargin': 19.43281151745337, 'StockTurnover': 0.9186980283295949, 'SalestoPurchaseRatio': 1.2412000701956123}  ... displaying 10 of 10692 total bound parameter sets ...  {'VendorNumber': 3960, 'VendorName': 'DIAGEO NORTH AMERICA INC', 'Brand': 6127, 'Description': 'The Club Strawbry Margarita', 'PurchasePrice': 1.47, 'ActualPrice': 1.99, 'Volume': 200.0, 'TotalPurchaseQuantity': 1.0, 'TotalPurchaseDollars': 1.47, 'TotalSalesPrice': 77.60999999999999, 'TotalSalesDollars': 143.28, 'TotalSalesQuantity': 72.0, 'TotalExciseTax': 15.120000000000008, 'FreightCost': 257032.07000000007, 'GrossProfit': 141.81, 'ProfitMargin': 98.97403685092128, 'StockTurnover': 72.0, 'SalestoPurchaseRatio': 97.46938775510205}, {'VendorNumber': 7245, 'VendorName': 'PROXIMO SPIRITS INC.', 'Brand': 3065, 'Description': 'Three Olives Grape Vodka', 'PurchasePrice': 0.71, 'ActualPrice': 0.99, 'Volume': 50.0, 'TotalPurchaseQuantity': 1.0, 'TotalPurchaseDollars': 0.71, 'TotalSalesPrice': 33.65999999999998, 'TotalSalesDollars': 85.13999999999999, 'TotalSalesQuantity': 86.0, 'TotalExciseTax': 4.459999999999998, 'FreightCost': 38994.78000000001, 'GrossProfit': 84.42999999999999, 'ProfitMargin': 99.16607939863754, 'StockTurnover': 86.0, 'SalestoPurchaseRatio': 119.91549295774647}]]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [59]:
# Replacing inf/-inf with 0
import numpy as np
vendor_sales_summary = vendor_sales_summary.replace([np.inf, -np.inf], np.nan).fillna(0)

In [60]:
vendor_sales_summary.to_sql(
    name='vendor_sales_summary',
    con=engine,
    if_exists="replace",
    index=False
)

10692